C_FLAGS = -I.. -DMODWINMM_EXPORTS ${CFLAGS}
L_FLAGS = -L.. -lwinmm ${LFLAGS}

MODEXT = .dll

BIN = ../modwinmm${MODEXT}

all: ${BIN}

${BIN}: modwinmm.o
	gcc -shared -o $@ $^ ${L_FLAGS}

modwinmm.o: modwinmm.c modwinmm.h
	gcc -c -g -Wall -Wextra $< -o $@ ${C_FLAGS}

clean:
	rm -f *.o

