C_FLAGS = -g -Wall `pkg-config --cflags glib-2.0` -DLIBMSK_EXPORTS ${CFLAGS}
L_FLAGS = `pkg-config --libs glib-2.0` -lm ${LFLAGS}

OBJ_TEST = msktestzone.o
OBJECTS  = mskmodule.o mskworld.o mskcontainer.o mskconstant.o mskoscillator.o \
           mskaddmul.o mskinstrument.o

MODEXT = .dll

BIN=../msk0${MODEXT}

all: ${BIN}

${BIN}: ${OBJECTS}
	gcc -shared -o $@ $^ ${L_FLAGS}

test: ${OBJECTS} ${OBJ_TEST}
	gcc -o test $^ ${L_FLAGS}

msk%.o: msk%.c msk0.h mskinternal.h
	gcc -c $< ${C_FLAGS}

clean:
	rm -f *.o
