C_FLAGS = -g -Wall `pkg-config --cflags glib-2.0` -DLIBMSK_EXPORTS ${CFLAGS}
L_FLAGS = `pkg-config --libs glib-2.0` -lm ${LFLAGS}

OBJ_TEST = msktestzone.o
OBJECTS  = mskmodule.o mskworld.o mskcontainer.o mskconstant.o mskoscillator.o \
           mskaddmul.o mskinstrument.o mskfactory.o msksaveload.o mskadapter.o

MODEXT = .dll
EXEEXT = .exe

BIN  = ../msk0${MODEXT}
TEST = benchmark${EXEEXT}


all: ${BIN} ${TEST}

${BIN}: ${OBJECTS}
	gcc -shared -o $@ $^ ${L_FLAGS}

${TEST}: ${OBJECTS} ${OBJ_TEST}
	gcc -o $@ $^ ${L_FLAGS}

msk%.o: msk%.c msk0.h mskinternal.h
	gcc -c $< ${C_FLAGS}

clean:
	rm -f *.o
