C_FLAGS = -Wall `pkg-config --cflags gtk+-2.0` ${CFLAGS}
L_FLAGS = `pkg-config --libs gtk+-2.0 gthread-2.0` ${LFLAGS}

BINEXT = .exe
MODEXT = .dll

OBJ1 = first.o events.o virkb.o process.o menu.o \
       gmsk${MODEXT} msk0$(MODEXT) modwinmm$(MODEXT)



all: synthtoy${BINEXT}

synthtoy$(BINEXT): ${OBJ1}
	gcc -o $@ ${OBJ1} ${L_FLAGS}

%.o: %.c header.h
	gcc -c -g -Wall $< ${C_FLAGS}

modwinmm$(MODEXT):
	@make -C mod-winmm -f Makefile.bak

msk0$(MODEXT):
	@make -C msk0 -f Makefile.bak

gmsk$(MODEXT):
	@make -C gmsk -f Makefile.bak

clean:
	make -C mod-winmm -f Makefile.bak clean
	make -C msk0 -f Makefile.bak clean
	make -C gmsk -f Makefile.bak clean
	rm -f *.o

.PHONY: msk0$(MODEXT) gmsk$(MODEXT) modwinmm$(MODEXT)
