C_FLAGS = -Wall `pkg-config --cflags gtk+-2.0`
L_FLAGS = `pkg-config --libs gtk+-2.0 gthread-2.0`

BINEXT = .exe
MODEXT = .dll

OBJ1 = first.o events.o virkb.o process.o mskeditor.o msk0$(MODEXT) modwinmm$(MODEXT)



all: first.ui first${BINEXT}

first$(BINEXT): ${OBJ1}
	gcc -o $@ ${OBJ1} ${L_FLAGS}

%.o: %.c
	gcc -c -g -Wall $< ${C_FLAGS}

first.ui: first.glade
	gtk-builder-convert first.glade first.ui

modwinmm$(MODEXT):
	@make -C mod-winmm -f Makefile.bak

msk0$(MODEXT):
	@make -C msk0 -f Makefile.bak

clean:
	make -C mod-winmm -f Makefile.bak clean
	make -C msk0 -f Makefile.bak clean
	rm -f *.o

.PHONY: msk0$(MODEXT) modwinmm$(MODEXT)
